#!/bin/bash


echo "SLURM_NODEID $SLURM_NODEID SLURM_NODEID $SLURM_NODEID"
echo "SLURM_NODEID $SLURM_NODEID SLURM_NNODES $SLURM_NNODES"
echo "SLURM_NODEID $SLURM_NODEID SLURM_JOB_NODELIST $SLURM_JOB_NODELIST"
echo "SLURM_NODEID $SLURM_NODEID SLURM_PROCID $SLURM_PROCID"
echo "SLURM_NODEID $SLURM_NODEID SLURM_NPROCS $SLURM_NPROCS"
